# Generated by Django 3.2.25 on 2024-04-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hardiness_zone',
            field=models.IntegerField(choices=[(0, 'Not applicable'), (1, 'Zone 1'), (2, 'Zone 2'), (3, 'Zone 3'), (4, 'Zone 4'), (5, 'Zone 5'), (6, 'Zone 6'), (7, 'Zone 7'), (8, 'Zone 8')], default=0),
        ),
    ]
